# Generated by Django 4.1.2 on 2022-10-09 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_status',
            field=models.IntegerField(choices=[(0, 'created'), (1, 'information received'), (2, 'in queue'), (3, 'in transit'), (4, 'available for pickup'), (5, 'delivered'), (6, 'canceled')], default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
