# Generated by Django 4.1.2 on 2022-10-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_company_options_alter_shipment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['created_at']},
        ),
    ]
