# Generated by Django 4.1.2 on 2022-10-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_shipment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='company_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_owners', to='shipments.company'),
        ),
    ]
