# Generated by Django 4.1.2 on 2022-10-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_company_description_alter_shipment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='delivery_status',
            field=models.IntegerField(choices=[('CREATED', 'created'), ('RECEIVED', 'information received'), ('IN QUEUE', 'in queue'), ('IN TRANSIT', 'in transit'), ('PICKUP', 'available for pickup'), ('DELIVERED', 'delivered'), ('CANCELED', 'canceled')], default='CREATED'),
        ),
    ]
