# Generated by Django 4.1.2 on 2022-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_alter_shipment_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='delivery_status',
            field=models.CharField(choices=[('CREATED', 'created'), ('RECEIVED', 'information received'), ('IN QUEUE', 'in queue'), ('IN TRANSIT', 'in transit'), ('PICKUP', 'available for pickup'), ('DELIVERED', 'delivered'), ('CANCELED', 'canceled')], default='CREATED', max_length=40),
        ),
    ]
