# Generated by Django 4.1.2 on 2022-10-19 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_rename_country_recipient_shipment_delivery_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
